analyzer:
  errors:
    todo: ignore
    prefer_const_constructors: info
    unnecessary_const: error
linter:
  rules:
    - unnecessary_await_in_return
    - unnecessary_null_checks
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unrelated_type_equality_checks
    - tighten_type_of_initializing_formals
    - always_declare_return_types
    - avoid_catching_errors
    - avoid_empty_else
    - empty_catches
    - missing_whitespace_between_adjacent_strings
    - camel_case_extensions
    - camel_case_types
    - file_names
    - leading_newlines_in_multiline_strings
    - prefer_final_in_for_each
    - prefer_final_locals
    - sized_box_shrink_expand
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_null_aware_method_calls
    - sort_constructors_first
    - always_use_package_imports
    - avoid_redundant_argument_values 
    - avoid_relative_lib_imports
    - avoid_returning_this
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - cancel_subscriptions
    - comment_references  
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - join_return_with_assignment
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_runtimeType_toString
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - only_throw_errors
    - prefer_constructors_over_static_methods
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_int_literals
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps
    - void_checks
    - use_colored_box
    - use_super_parameters
    - unawaited_futures
    - cast_nullable_to_non_nullable
    - unnecessary_lambdas